### ISSUE TITLE
OpenFL 3 can't compile for native targets (Lib.packageName)

### ISSUE THREAD

**Issue by eliasku** [fbricker/haxe-ga#13]
there is no support for these info in openfl 3 anymore, actually we can discuss and check major version of openfl and make more tricky checks for preprocessor... 

I've also created issue on openfl to clarify the status and plans on implementation of these fields. https://github.com/openfl/openfl/issues/719

*Or the simplest solution is just drop that functionality from haxe-ga, and provide some customPackage setter outside of main module.*

**Comment by fbricker** [comment]
Done! Now haxe-ga it's compatible with both (openfl-legacy and openfl-next). Thanks!
